### PR TITLE
correctly read variables

### PR DESCRIPTION
**Pull request by thesebas**
variables passed to action with `with` are converted to env variables prefixed with `INPUT_` [see documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs)

### CODE REVIEW

**Comment by distributhor** [comment]
The update to the documentation that changed 'env' to 'with' (which I merged too quickly without proper consideration) and now the subsequent change required by this pull request, is actually not backwards compatible, and will break things for existing users of this action. It fundamentally changes how the function works. 

While changing 'env' to 'with' might be an improvement or a more semantically correct way of doing things, I cannot currently do such a release without making it a new major version. For the moment I will revert the documentation change and not merge this change, but will include the JSON improvement. Once this has been released on V3 I can consider whether 'env' should change to 'with', as a better way to handle secrets. If the change makes sense as an improvement in the right direction for the long run, then it must be done in a new V4.

**Comment by distributhor** [comment]
I will revise the following documentation (below) again, to try and establish the best practice for handling this currently. 
https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by thesebas** [comment]
[`06ff9f3` (#44)](https://github.com/distributhor/workflow-webhook/pull/44/commits/06ff9f3d581221eeb06f1bc89503462a66a7f682) should make it backward compatible

**Comment by distributhor** [comment]
Thanks, and apologies for the long delay on this. I was hoping to get to this far sooner, but life. I will release a new version after some testing to confirm it all, either today (if time allows) or otherwise on the weekend.

**Pull request merged**
